apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    name: postgress-deploy
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgress-pod
      app: demo-voting-app
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgress-pod
        app: demo-voting-app
    spec:
      containers:
        - name: postgres
          image: postgres:56
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-voting-app
    name: postgress-deploy
  name: postgres-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app
      name: postgress-pod
  template:
    metadata:
      labels:
        app: demo-voting-app
        name: postgress-pod
      name: postgres-pod
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        image: postgres:12
        name: postgres
        ports:
        - containerPort: 5432
